# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket = "theanotherwise-aws-tfstates"
    prefix = "environments/theanotherwise/eu-central-1/compute/eks-primary/node-role"
  }
}
