# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket = "theanotherwise-aws-tfstates"
    prefix = "environments/theanotherwise/eu-west-1/network/vpc-primary/vpc"
  }
}
