# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region              = "eu-central-1"
  allowed_account_ids = ["674403012652"]

  default_tags {
    tags = {
      ManagedBy  = "terragrunt"
      Account    = "theanotherwise"
      Repository = "terraform-aws-demo"
    }
  }
}
